pipeline {
    agent any
    stages {
        stage ('build') {
            steps {
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git';
                sh 'mvn -B -DskipTests clean package';
            }
        }
    }
}